### ISSUE TITLE
Changing Modes keeps old mode stagnant

### ISSUE THREAD

**Issue by poodull** [poodull/Cartographer2#3]
If you set a floor's origin, then go to "Select Editor" mode, it keeps you in origin mode.  Even if you click any action buttons (arrow, pan, etc)

**Comment by poodull** [comment]
A similar thing happens going from origin to walls...  it stays on origin until you actively select 'create wall' action.  It should default to the first action in the mode.

**Comment by Vamsikri05** [comment]
Fixed
