### ISSUE TITLE
Select Walls

### ISSUE THREAD

**Issue by poodull** [poodull/Cartographer2#8]
Select walls does not seem to be working.  We have to change its behavior to be more like photoshop and other painting programs.

modes for select:

Single click (mouse click with no drag):  User clicks on a wall line or anchor without dragging.  That wall or anchor is now 'selected'.  A visible change should be apparent -- thick, brighter lines and voxels.

Click and drag (mouse down + drag):  A) If the mouse down was NOT on a voxel or selectable item, then an anchor point voxel is placed at the initial event location and a selection box is generated from that anchor until the user releases the mouse button.  Any walls or wall anchors in that selection box are now 'selected'... visual queues, etc.
B) If the mouse down DID land on a wall or wall anchor while dragging, the entire wall (2 anchors and line) or the anchor clicked on is now actively moving with the drag action.  Mouse up ends the movement of the wall, anchor, leaving the wall/anchor(s) selected.

**Comment by Vamsikri05** [comment]
I prefer having a separate icon for moving rather than including that in the select option as it would complicate things for selection. For moving user has to have the mouse down and either mode may get selected, within a click difference of pixels.

**Comment by poodull** [comment]
I see that select does work now.  I can create a box around walls and then press the delete button which removes them.  But we need to change the behavior to something more normalized like the post above.

Single click to select, or click and drag to create selection criteria. 
Selected items change their appearance.
Delete key actively deletes (backspace too).
Escape un-selects.


As far as having select and move as separate actions, why wouldn't you just throw a click-select-drag straight into move mode?  There doesn't seem to be a move mode button for walls, however.

**Comment by poodull** [comment]
Very close.  Select is starting work as it should.  A couple of minor tweaks to get it perfect:

1) A selection box selects all end points (voxels) within the box. A wall with both end points selected highlights the wall that connects them also (this works right now).  
ie: I have 2 walls (4 end points).  I draw a box that selects 3 end points (1 full wall and a point from the other wall).  I should see the wall with both end points selected (works) AND the 3rd end point from the other wall selected (but not the 2nd wall, nor the 4th end point).

2) A selected item or items should all move together when dragged.  If I select a wall via the selection box, then click and drag an endpoint, everything that was selected should move.  Right now only the dragged end point moves even though there is other items highlighted as selected.
ie: I have 2 walls (4 end points).  I draw a box that selects 3 end points (1 full wall and a point from the other wall). If click and drag any one of the 3 selected end points all three end points should move the same delta.  This should also work for dragging a wall (the 3rd point should also move)

3) The Escape key should leave the mode in Select, but cancel the selection.  Right now the mode is changed to NO MODE and the selected item remain highlighted.

**Comment by Vamsikri05** [comment]
Fixed.
